//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeDevPnP.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CanProvisionIssuesMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanProvisionIssuesMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeDevPnP.Core.CanProvisionIssuesMessages", typeof(CanProvisionIssuesMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template requires a fully provisioned App Catalog. The App Catalog on your tenant has been created within the last 2 hours. Please wait a bit longer to provision the template..
        /// </summary>
        internal static string App_Catalog_Not_Yet_Fully_Provisioned {
            get {
                return ResourceManager.GetString("App_Catalog_Not_Yet_Fully_Provisioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to provision the template you need to have an App Catalog in your tenant. Please, create one (for instructions you can read this document: https://go.microsoft.com/fwlink/?linkid=2087251), wait up to 2 hours, and try again..
        /// </summary>
        internal static string Missing_App_Catalog {
            get {
                return ResourceManager.GetString("Missing_App_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to provision the template you need to have Full Control permissions on the App Catalog in your tenant. Please, configure the App Catalog security settings, and try again..
        /// </summary>
        internal static string Missing_Permissions_for_App_Catalog {
            get {
                return ResourceManager.GetString("Missing_Permissions_for_App_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to provision the template you need to be Term Store Administrator. Please, change the Term Store settings (for instructions you can read this document: https://go.microsoft.com/fwlink/?linkid=2087340) and try again..
        /// </summary>
        internal static string Term_Store_Not_Admin {
            get {
                return ResourceManager.GetString("Term_Store_Not_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to provision the template you need Tenant Admin rights. Please ask a Tenant Admin to provision the template for you or to promote yourself to a Tenant Admin..
        /// </summary>
        internal static string User_Is_Not_Tenant_Admin {
            get {
                return ResourceManager.GetString("User_Is_Not_Tenant_Admin", resourceCulture);
            }
        }
    }
}
