
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET XACT_ABORT ON
GO


BEGIN TRANSACTION
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[TestConfigurationSet] DROP CONSTRAINT [FK_TestCategoryTestConfiguration]
GO

DROP INDEX [IX_FK_TestCategoryTestConfiguration] ON [dbo].[TestConfigurationSet]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[TestConfigurationSet] ALTER COLUMN [TestCategory_Id] [int] NOT NULL
GO

CREATE NONCLUSTERED INDEX [IX_FK_TestCategoryTestConfiguration] ON [dbo].[TestConfigurationSet]
(
	[TestCategory_Id] ASC
)
WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[TestConfigurationSet] WITH CHECK ADD CONSTRAINT [FK_TestCategoryTestConfiguration] FOREIGN KEY
(
	[TestCategory_Id]
)
REFERENCES [dbo].[TestCategorySet]
(
	[Id]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO


COMMIT TRANSACTION
GO

